stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script: mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/

test:
  stage: test
  script: mvn test

deploy:
  stage: deploy
  variables:
    PORT: 5000 
  script: 
    - sh target/bin/simplewebapp


