stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script: mvn compile
  artifacts:
    paths:
      - target/  

test:
  stage: test
  script: mvn test
  artifacts:
    paths:
      - target/  

deploy:
  stage: deploy
  environment:
    name: virtualmachine
    url: 146.169.44.190:5000
  artifacts:
    paths:
      - target/  
  script: 
    - export PORT=5000
    - sh target/bin/simplewebapp


