stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script: mvn compile 

test:
  stage: test
  script: mvn test

# run_on_vm:
#   stage: deploy
#   variables:
#     PORT: 5000
#   script:
#     - sh target/bin/simplewebapp &>/dev/null &

deploy_to_heroku:
  stage: deploy
  script:
    - mvn package -Dmaven.test.skip=true
    - dpl --provider=heroku --app=cg3417-simplewebapp --api-key=$HEROKU_API_KEY
  only:
    - master 
